#!/bin/bash

# list of global variables that hold default values when installing arch

PS3='Enter option: '
NETWORK_DEVICE=''
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"

# EDITOR {{{
EDITOR='nano'
# }}}
# MIRRORLIST {{{
MIRRORLIST='sort by download speed'
# }}}
# PARTITION {{{
DEVICE='/dev/sda'

BOOT_PARTITION=''
ROOT_PARTITION=''
HOME_PARTITION=''
SWAP_PARTITION=''

ROOT_SIZE='30G'
HOME_SIZE='100%FREE'
SWAP_SIZE='4G'

FORMAT_BOOT_PARTITION=0
FORMAT_HOME_PARTITION=0

MOUNTPOINT='/mnt'
# }}}
# LOCALE {{{
LOCALE='fr_FR'
# }}}
# TIMEZONE {{{
ZONE='Europe'
SUBZONE='Paris'
# }}}
# HARDWARE CLOCK {{{
HARDWARE_CLOCK='UTC'
# }}}
# KEYMAP {{{
KEYMAP='fr-latin9'
# }}}
# HOSTNAME {{{
HOSTNAME='nosirusPC'
# }}}
# USERNAME {{{
USERNAME='nosirus'
# }}}
# DESKTOP ENVIRONMENT {{{
DESKTOP_ENVIRONMENT='KDE'
# }}}
# DOTFILES {{{
DOTFILES='NearHuscarl dotfiles'
# }}}
